# Generated by Django 5.1.1 on 2024-09-17 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_pets_allowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='price_per_nigth',
            new_name='price_per_night',
        ),
    ]
